'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BTTButton from './components/BTTButton'
import Navbar from "./components/Navbar";
import TopNavbar from "./components/TopNavbar";
import MainFooter from "./components/MainFooter";
import StickyFooter from "./components/StickyFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopNavbar/>
        <Navbar/>
        {children}
        <BTTButton/>
        <MainFooter/>
        <StickyFooter/>
      </body>
    </html>
  );
}
